# Generated by Django 5.1.2 on 2024-10-25 18:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MgiCandles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('trade_signal', models.CharField(blank=True, choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=4, null=True)),
                ('is_active', models.BooleanField(blank=True, default=False, null=True)),
                ('idea_candle', models.ImageField(blank=True, null=True, upload_to='idea_candles/')),
                ('line_graph_candle', models.ImageField(blank=True, null=True, upload_to='line_graph_candles/')),
                ('signal_candle', models.ImageField(blank=True, null=True, upload_to='signal_candles/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
